name: ci

on: [push]

# Allow one run of this workflow per branch and cancel existing runs if triggered again
concurrency:
  group: inkysharp-ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['9.0.x', '8.0.x']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            9.0.x
            8.0.x
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./source
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./source
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./source
