name: "Publish Release"

on:
  workflow_dispatch

# Allow one run of this workflow per branch and cancel existing runs if triggered again
concurrency:
  group: inkysharp-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # Needed to push tags

jobs:
  release:
    runs-on: ubuntu-latest
    environment: NuGet
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0' # Load entire history
      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - run: dotnet tool restore
        working-directory: ./source
      - name: Generate Version
        id: generate-version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          dotnet tool run versionize
          echo "RELEASE_VERSION_NUMBER=$(dotnet tool run versionize inspect)" >> $GITHUB_OUTPUT
          git push --follow-tags
          git fetch --tags origin
        working-directory: ./source
      - run: dotnet restore
        working-directory: ./source
      - run: dotnet build --no-restore -c Release -p:Version=${{ steps.generate-version.outputs.RELEASE_VERSION_NUMBER }}
        working-directory: ./source
      - run: dotnet pack --no-build --no-restore --nologo --output=dist -c Release
        working-directory: ./source
      - run: gh release create "v${{ steps.generate-version.outputs.RELEASE_VERSION_NUMBER }}" --notes-file CHANGELOG.md "dist/InkySharp.Driver.${{ steps.generate-version.outputs.RELEASE_VERSION_NUMBER }}.nupkg"
        working-directory: ./source
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Publish to NuGet
        run:
          dotnet nuget push "InkySharp.Driver.${{ steps.generate-version.outputs.RELEASE_VERSION_NUMBER }}.nupkg" --api-key=${{ secrets.NUGET_API_KEY }} --source=https://api.nuget.org/v3/index.json --skip-duplicate
        working-directory: ./source/dist